AirBnB/AirBnB/Controllers/AreasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AirBnB.Data;
using AirBnB.Models;
using Microsoft.AspNetCore.Authorization;
using System.Data;

namespace AirBnB.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AreasController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AreasController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Areas
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Areas.Include(a => a.City);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Areas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Areas == null)
            {
                return NotFound();
            }

            var area = await _context.Areas
                .Include(a => a.City)
                .FirstOrDefaultAsync(m => m.AreaId == id);
            if (area == null)
            {
                return NotFound();
            }

            return View(area);
        }

        // GET: Areas/Create
        public IActionResult Create()
        {
            ViewData["CityId"] = new SelectList(_context.Cities, "CityId", "CityName");
            return View();
        }

        // POST: Areas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("AreaName,CityId")] Area area,IFormFile imgFile )
        {
            if (ModelState.IsValid)
            {
                var lastrow = _context.Areas.OrderByDescending(u => u.AreaId).FirstOrDefault();
                if (lastrow != null)
                {
                    int lastid = lastrow.AreaId;
                    string fileName = (lastid + 1).ToString() + "." + imgFile.FileName.Split(".").Last();
                    area.AreaImg = fileName;
                    using (var fs = System.IO.File.Create("wwwroot/AreaImgs/" + fileName))
                    {
                        imgFile.CopyTo(fs);
                    }
                    _context.Add(area);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    string fileName = area.AreaId.ToString() + "." + imgFile.FileName.Split(".").Last();
                    area.AreaImg = fileName;
                    using (var fs = System.IO.File.Create("wwwroot/AreaImgs/" + fileName))
                    {
                        imgFile.CopyTo(fs);
                    }
                    _context.Add(area);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
            }
            ViewData["CityId"] = new SelectList(_context.Cities, "CityId", "CityName", area.CityId);
            return View(area);
        }

        // GET: Areas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Areas == null)
            {
                return NotFound();
            }

            var area = await _context.Areas.FindAsync(id);
            if (area == null)
            {
                return NotFound();
            }
            ViewData["CityId"] = new SelectList(_context.Cities, "CityId", "CityName", area.CityId);
            return View(area);
        }

        // POST: Areas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("AreaId,AreaName,CityId")] Area area,IFormFile imgFile)
        {
            if (id != area.AreaId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (imgFile != null)
                    {
                        string fileName = area.AreaId.ToString() + "." + imgFile.FileName.Split(".").Last();
                        if (System.IO.File.Exists("wwwroot/AreaImgs/" + fileName))
                        {
                            System.IO.File.Delete("wwwroot/AreaImgs/" + fileName);
                        }
                        using (var fs = System.IO.File.Create("wwwroot/AreaImgs/" + fileName))
                        {
                            imgFile.CopyTo(fs);
                        }
                        area.AreaImg = fileName;
                    }
                    _context.Update(area);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AreaExists(area.AreaId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CityId"] = new SelectList(_context.Cities, "CityId", "CityName", area.CityId);
            return View(area);
        }

        // GET: Areas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Areas == null)
            {
                return NotFound();
            }

            var area = await _context.Areas
                .Include(a => a.City)
                .FirstOrDefaultAsync(m => m.AreaId == id);
            if (area == null)
            {
                return NotFound();
            }

            return View(area);
        }

        // POST: Areas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Areas == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Areas'  is null.");
            }
            var area = await _context.Areas.FindAsync(id);
            if (area != null)
            {
                string fileName = area.AreaImg;
                if (System.IO.File.Exists("wwwroot/AreaImgs/" + fileName))
                {
                    System.IO.File.Delete("wwwroot/AreaImgs/" + fileName);
                }
                _context.Areas.Remove(area);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AreaExists(int id)
        {
          return _context.Areas.Any(e => e.AreaId == id);
        }
    }
}

AirBnB/AirBnB/Controllers/RolesController.cs
using AirBnB.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Data;

namespace AirBnB.Controllers
{

    [Authorize(Roles = "Admin")]
    public class RolesController : Controller
    {
        //i need object of roleManager to control the all roles
        private readonly RoleManager<IdentityRole> _roleManager;

        //then i make injection ctor to take obj of roleManger from DIC to initialize my _roleManager obj 
        public RolesController(RoleManager<IdentityRole> roleManager)
        {
            _roleManager = roleManager;
        }
        public async Task<IActionResult> Index()
        {
            //store all roles objs from _roleManager as a list into roles
            var roles = await _roleManager.Roles.ToListAsync();
            return View(roles);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        //to prevent cross-site request forgery attacks.
        public async Task<IActionResult> Add(RoleFormViewModel model)
        {
            if (!ModelState.IsValid)
            {
                //return view (index)
                return View("index", await _roleManager.Roles.ToListAsync());
            }
            var roleExist = await _roleManager.RoleExistsAsync(model.Name);
            if (roleExist)
            {
                ModelState.AddModelError("Name", "Role is Exist..!");
                return View("index", await _roleManager.Roles.ToListAsync());
            }
            //trim to remove the spaces
            await _roleManager.CreateAsync(new IdentityRole(model.Name.Trim()));
            //return to action (index)
            return RedirectToAction("index");
        }

    }
}

AirBnB/AirBnB/Controllers/UsersController.cs
using AirBnB.Data;
using AirBnB.Models;
using AirBnB.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Data;

namespace AirBnB.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UsersController : Controller
    {
        //to control all users
        private readonly UserManager<AppUser> _UserManager;
        //to control all roles
        private readonly RoleManager<IdentityRole> _RoleManager;

        //injection ctor its parameter initialized by Dic that send them
        public UsersController(UserManager<AppUser> UserManager, RoleManager<IdentityRole> RoleManager)
        {
            _UserManager = UserManager;
            _RoleManager = RoleManager;
        }
        public IActionResult Index()
        {
            // but i don't need the all data of users i want the only data that in UserViewModel
            //code:
            //var users = await _UserManager.Users.ToListAsync();

            //then i selected wanted data only
            var users =_UserManager.Users.Select(user => new UserViewModel
            {
                Id = user.Id,
                FirstName = user.FirstName,
                LastName = user.LastName,
                Email = user.Email,
                Roles = _UserManager.GetRolesAsync(user).Result
            }).ToList();

             return View(users);
        }

        [HttpGet]
        public async Task<IActionResult> ManageRoles(string userId)
        {
            var user = await _UserManager.FindByIdAsync(userId);
            if (user == null)
            {
                return NotFound();
            }
            var roles = await _RoleManager.Roles.ToListAsync();

            var viewModel = new UserRolesViewModel
            {
                UserId = user.Id,
                UserName = user.UserName,
                Roles = roles.Select(role => new RoleViewModel
                {
                    RoleName = role.Name,
                    IsSelected = _UserManager.IsInRoleAsync(user, role.Name).Result,
                }).ToList()
            };
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ManageRoles(UserRolesViewModel model)
        {
            var user = await _UserManager.FindByIdAsync(model.UserId);
            if (user == null)
            {
                return NotFound();
            }
            //first condition if user check role (x) and he exactly has role (x) ==> no action
            //second condition if user check role (x) and he hasn't role (x) ==> add role
            //third condition if user unchecked role (x) and he exactly has't role (x) ==> no action
            //fourth condition if user unchecked role (x) and he has role (x) ==> remove role

            //first select the user with all his roles only
            var userRoles = await _UserManager.GetRolesAsync(user);

            foreach (var role in model.Roles)
            {
                //fourth condition => user has this role but he unselected this role => remove role
                if (userRoles.Any(r => r == role.RoleName) && !role.IsSelected)
                {
                    await _UserManager.RemoveFromRoleAsync(user, role.RoleName);
                }
                //second condition => user hasn't this role but he selected this role => add role
                if (!userRoles.Any(r => r == role.RoleName) && role.IsSelected)
                {
                    await _UserManager.AddToRoleAsync(user, role.RoleName);
                }
            }
            return RedirectToAction(nameof(Index));
        }
        
    }
}

AirBnB/AirBnB/Views/Shared/_Layout.cshtml
@inject SignInManager<AppUser> SignInManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AirBnB</title>
    @*Bootstrap link*@
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    @*<link rel="stylesheet" href="~/AirBnB.styles.css" asp-append-version="true" />*@

    @*google fonts*@
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@300;400;700&family=Fraunces:opsz,wght@9..144,700&family=Montserrat:wght@500;700&family=Open+Sans:wght@300;400;500;600;700;800&family=Work+Sans:wght@200;300;400;500;600;700;800&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Charm:wght@700&family=Cinzel:wght@500;600;700;800;900&family=Mulish:ital,wght@0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,1000;1,200;1,300;1,400;1,500&family=Ubuntu:ital,wght@0,300;0,400;0,500;0,700;1,300&display=swap" rel="stylesheet">
    @*normalize file*@
    <link rel="stylesheet" href="~/css/normalize.css">
    @*fonts awesome icons library*@
    <link rel="stylesheet" href="~/css/all.min.css">
    @*booking.css*@
    <link rel="stylesheet" href="~/css/Booking.css">
    @*main css file *@
    <link rel="stylesheet" href="~/css/main.css">
    @*maps css file*@
    <link rel="stylesheet" href="./css/maps.css">
   
</head>
<body>
   @*header*@
<!-- Start header -->
    <div class="header" id="header">
        <div class="container">
            <a asp-controller="Home" asp-action="index"><i class="fa-brands fa-airbnb" id="logo"></i></a>
            <ul class="main-nav">
                <partial name="_LoginPartial" />
                @if (SignInManager.IsSignedIn(User))
                {
                    <li><a asp-controller="Properties" asp-action="Create">Create Property</a></li>
                }
                <li><a asp-controller="Properties" asp-action="index">Properties</a></li>
                <li><a asp-controller="Home" asp-action="index">Home</a></li>
                @if (User.IsInRole("Admin"))
                {
                    <li>
                        <a href="#">Admin</a>
                        <!-- Start Mega-Menu -->
                        <div class="mega-menu">
                            <div class="image">
                                <img src="~/LayoutImgs/Admin.png" alt="Admin Image">
                            </div>
                            <ul class="links">
                                <li>
                                    <a asp-area="" asp-controller="Users" asp-action="index"><i class="fa-solid fa-users"></i>Manage Users</a>
                                </li>
                                <li>
                                    <a asp-controller="Amenities" asp-action="index"><i class="fa-solid fa-wifi"></i>Amenities</a>
                                </li>
                                <li>
                                    <a asp-controller="Cities" asp-action="index"><i class="fa-solid fa-tree-city"></i>Cities</a>
                                </li>
                                <li>
                                    <a asp-controller="Properties" asp-action="AdminIndex"><i class="fa-solid fa-house"></i>Manage Properties</a>
                                </li>
                            </ul>
                            <ul class="links">
                                <li>
                                    <a asp-area="" asp-controller="Roles" asp-action="index"><i class="fa-solid fa-gears"></i>Manage Roles</a>
                                </li>
                                <li>
                                    <a asp-controller="Categorays" asp-action="index"><i class="fa-solid fa-sliders"></i>Categoraies</a>
                                </li>
                                <li>
                                    <a asp-controller="Areas" asp-action="index"><i class="fa-solid fa-city"></i>Areas</a>
                                </li>
                                <li>
                                    <a asp-controller="Bookings" asp-action="index"><i class="fa-solid fa-sliders"></i>Manage Booking</a>
                                </li>
                                <li>
                                    <a asp-controller="Reviews" asp-action="index"><i class="fa-solid fa-comments"></i>Manage Reviews</a>
                                </li>
                        </div>
                        <!-- End Mega-Menu -->
                    </li>
                }
                
            </ul>
        </div>
    </div>
<!-- End header -->


   @*start body*@
            @RenderBody()
   @*end body*@


   @*footer*@
<!-- Start Footer  -->  
    <footer class="bg-light text-dark pt-5 pb-4 footer">
      <div class="container text-center text-md-left">
        <div class="row text-center text-md-left">
          <div class="col-md-3 col-lg-3 col-xl-3 mx-auto mt-3">
            <h6 class="text-uppercase mb-4 font-weight-bold text-Dark">support</h6>
            <p><a href="#" class="text-dark" style="text-decoration:none">Help Center</a></p>
            <p><a href="#" class="text-dark" style="text-decoration:none">AirCover</a></p>
            <p><a href="#" class="text-dark" style="text-decoration:none">Supporting people with disabilities</a></p>
            <p><a href="#" class="text-dark" style="text-decoration:none">Cancellation options</a></p>
            <p><a href="#" class="text-dark" style="text-decoration:none">Our COVID-19 Response</a></p>
            <p><a href="#" class="text-dark" style="text-decoration:none">Report a neighborhood concern</a></p>
          </div>
          <div class="col-md-3 col-lg-3 col-xl-3 mx-auto mt-3">
            <h6 class="text-uppercase mb-4 font-weight-bold text-Dark">Community</h6>
            <p><a href="#" class="text-dark" style="text-decoration:none">Airbnb.org: disaster relief housing</a></p>
            <p><a href="#" class="text-dark" style="text-decoration:none">Combating discriminatino</a></p>
          </div>
          <div class="col-md-3 col-lg-3 col-xl-3 mx-auto mt-3">
            <h6 class="text-uppercase mb-4 font-weight-bold text-Dark">Hosting</h6>
            <p><a href="#" class="text-dark" style="text-decoration:none">Airbnb your home</a></p>
            <p><a href="#" class="text-dark" style="text-decoration:none">AirCover for Hosts</a></p>
            <p><a href="#" class="text-dark" style="text-decoration:none">Explore hosting resources</a></p>
            <p><a href="#" class="text-dark" style="text-decoration:none">Visit our community forum</a></p>
            <p><a href="#" class="text-dark" style="text-decoration:none">How to host responsibly</a></p>
          </div>
          <div class="col-md-3 col-lg-3 col-xl-3 mx-auto mt-3">
            <h6 class="text-uppercase mb-4 font-weight-bold text-Dark">Airbnb</h6>
            <p><a href="#" class="text-dark" style="text-decoration:none">Newsroom</a></p>
            <p><a href="#" class="text-dark" style="text-decoration:none">Learn about new features</a></p>
            <p><a href="#" class="text-dark" style="text-decoration:none">Letter from our founders</a></p>
            <p><a href="#" class="text-dark" style="text-decoration:none">Careers</a></p>
            <p><a href="#" class="text-dark" style="text-decoration:none">Investors</a></p>
            <p><a href="#" class="text-dark" style="text-decoration:none">Gift Cards</a></p>
          </div>
          <hr class="mb-4">
          <div class="row align-items-center">
            <div class="col-md-7 col-lg-8">
              <span>© 2023 Airbnb, Inc. </span>
              <a href="#" class="text-dark" style="text-decoration:none">. Terms</a>
              <a href="#" class="text-dark" style="text-decoration:none">. Sitemap</a>
              <a href="#" class="text-dark" style="text-decoration:none">. Privacy</a>
              <a href="#" class="text-dark" style="text-decoration:none">. Your Privacy Choices</a>
            </div>
            <div class="col-md-3 col-md-4 ">
              <div class="text-center text-md-right">
                <i class="fa-solid fa-globe"></i>
                <span>
                  English (US) </span>
                <a href="https://www.facebook.com/airbnbuk/?brand_redir=324826532457">
                <i class="fa-brands fa-facebook"></i></a>
                <a href="https://twitter.com/airbnb"><i class="fa-brands fa-twitter"></i></a>
                <a href="https://www.instagram.com/airbnb/"><i class="fa-brands fa-instagram"></i></a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </footer>
<!-- End Footer -->

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/zego-zim-web/index.js" asp-append-version="true"></script>
    <script>
        function previewBeforeUpload(id) {
            document.querySelector("#" + id).addEventListener("change", function (e) {
                if (e.target.files.length == 0) {
                    return;
                }
                let file = e.target.files[0];
                let url = URL.createObjectURL(file);
                var img = document.querySelector("#" + id + "-preview img");
                img.src = url;
            });
        }

        previewBeforeUpload("file-1");
    </script>
    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>