AirBnB/AirBnB/Models/Property.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace AirBnB.Models
{
    public class Property
    {
        [Key]
        public int PropertyId { get; set; }
        [Required, MaxLength(200), MinLength(5)]
        public string PropertyTitle { get; set; }
        [MaxLength(450)]
        public string PropertyDescription { get; set; }
        [Required]
        public int PropertyCapacity { get; set; }
        [Required]
        public int PropertyBedsNum { get; set; }
        [Required]
        public int PropertyBedRooms { get; set; }
        [Required]
        public int PropertyBath { get; set; }
        [Required]
        public int PropertyPricePerNight { get; set; }
        [MaxLength(450)]
        public string PropertyHostInfo { get; set; }
        [ForeignKey("AppUser")]
        [Required]
        public string AppUserId { get; set; }
        [ForeignKey("Area")]
        [Required]
        public int AreaId { get; set; }
        [ForeignKey("Categoray")]
        [Required]
        public int CategorayId { get; set; }
        public bool Accepted { get; set; } = false;
        //NP
        public AppUser AppUser { get; set; }
        public Area Area { get; set; }
        public Categoray Categoray { get; set; }
        public ICollection<Booking> Bookings { get; set; } = new HashSet<Booking>();
        public ICollection<PropertyImg> PropertyImgs { get; set; } = new HashSet<PropertyImg>();
        public ICollection<Amenity> Amenities { get; set; } = new HashSet<Amenity>();
        public ICollection<Review> Reviews { get; set; } = new HashSet<Review>();

    }
}

AirBnB/AirBnB/Controllers/PropertiesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AirBnB.Data;
using AirBnB.Models;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;


namespace AirBnB.Controllers
{
    public class PropertiesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PropertiesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Properties
        public async Task<IActionResult> Index()
        {
            var PropList = _context.Properties.Include(z => z.AppUser).Include(z => z.Area).ThenInclude(z => z.City).Include(z => z.Categoray).Include(z => z.PropertyImgs).Where(a=>a.Accepted==true);
         
            var categories = _context.Categoraies;
            ViewBag.cat = categories;
            return View(await PropList.ToListAsync());
        }

        // GET: Properties/Details/5
        public async Task<IActionResult> Details(int? id)
        {

            if (id == null || _context.Properties == null)
            {
                return NotFound();
            }
            ViewBag.flag = true;
            if (TempData["x"]!=null)
            {
                ViewBag.flag = false;
            }
            //code to get the current user id
            ViewData["userid"] = this.User.FindFirstValue(ClaimTypes.NameIdentifier);

            //code to get the selected property id
            ViewData["SelectedPropertyId"] = id;
            //code to get the current user id
            ViewData["userid"] = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            ViewData["r"] = false;
            Booking z = null;
            var b = _context.Bookings.ToArray();
            for(int i = 0; i < b.Length; i++)
            {
                if (b[i].AppUserId == (string)ViewData["userid"] && b[i].PropertyId == (int)ViewData["SelectedPropertyId"] && DateTime.Today > b[i].CheckOutDate)
                {
                    ViewData["r"] = true;
                    z = b[i];
                }
            }
            ViewData["z"] = z;


            var SelectedProp = _context.Properties.FirstOrDefault(x => x.PropertyId == id);
            ViewData["PropertyCapacity"] = SelectedProp.PropertyCapacity;

            var @property = await _context.Properties
                .Include(z => z.AppUser)
                .Include(z => z.Categoray)
                .Include(q => q.Reviews)
                .Include(z => z.PropertyImgs)
                .Include(a => a.Amenities)
                .Include(z => z.Area)
                .ThenInclude(z => z.City)
                .FirstOrDefaultAsync(m => m.PropertyId == id);

            ViewBag.reviews = _context.Reviews;
            ViewBag.areas = _context.Areas;
            if (@property == null)
            {
                return NotFound();
            }

            return View(@property);
        }

        // GET: Properties/Create
        public IActionResult Create()
        {
            ViewBag.cat = _context.Categoraies;
            ViewData["userid"] = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            ViewData["AppUserId"] = new SelectList(_context.Users, "Id", "Id");
            ViewData["AreaId"] = new SelectList(_context.Areas, "AreaId", "AreaName");
            ViewData["CategorayId"] = new SelectList(_context.Categoraies, "CategorayId", "CategorayName");
            ViewData["AmenityId"] = new SelectList(_context.Amenities, "AmenityId", "AmenityId");
            ViewBag.Amenity = _context.Amenities.ToList();
            return View();
        }

        // POST: Properties/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PropertyId,PropertyTitle,PropertyDescription,PropertyCapacity,PropertyBedsNum,PropertyBedRooms,PropertyBath,PropertyPricePerNight,PropertyHostInfo,AppUserId,AreaId,CategorayId")] Property @property , IFormFile[] propImg , int[] amenity)
        {
            if (ModelState.IsValid)
            {
                for (int i = 0; i < amenity.Length; i++)
                {
                    var x = _context.Amenities.Find(amenity[i]);
                    @property.Amenities.Add(x);
                }
                _context.Add(@property);
                await _context.SaveChangesAsync();
            }
            if (propImg == null)
            {
                ModelState.AddModelError("", "no image uploaded , plz upload image");
            }
            else
            {

                for (int i = 0,count=0; i < propImg.Length && count<propImg.Length; i++,count++)
                {
                    string filename;
                    PropertyImg p = new PropertyImg();
                    PropertyImg x = _context.PropertyImgs.OrderByDescending(u => u.PropertyId).FirstOrDefault();

                    if (x != null)
                    {
                        filename = @property.PropertyTitle + (x.PropertyId +count).ToString() + "." + propImg[i].FileName.Split(".").Last();

                        p.ImgSrc = filename;
                        p.PropertyId = @property.PropertyId;
                        _context.PropertyImgs.Add(p);
                        await _context.SaveChangesAsync();

                        using (var fs = System.IO.File.Create("wwwroot/Images/" + filename))
                        {
                            propImg[i].CopyTo(fs);
                        }
                        
                    }
                    else
                    {
                        filename = i.ToString() + "." + propImg[i].FileName.Split(".").Last();

                        p.ImgSrc = filename;
                        p.PropertyId = @property.PropertyId;
                        _context.PropertyImgs.Add(p);
                        await _context.SaveChangesAsync();
                        using (var fs = System.IO.File.Create("wwwroot/Images/" + filename))
                        {
                            propImg[i].CopyTo(fs);
                        }
                    }

                }
                return RedirectToAction(nameof(Index));
            }
            
            ViewData["AppUserId"] = new SelectList(_context.Users, "Id", "Id", @property.AppUserId);
            ViewData["AreaId"] = new SelectList(_context.Areas, "AreaId", "AreaName", @property.AreaId);
            ViewData["CategorayId"] = new SelectList(_context.Categoraies, "CategorayId", "CategorayName", @property.CategorayId);
            return View(@property);
        }

        // GET: Properties/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Properties == null)
            {
                return NotFound();
            }

            var @property = await _context.Properties.FindAsync(id);
            if (@property == null)
            {
                return NotFound();
            }
            ViewData["AppUserId"] = new SelectList(_context.Users, "Id", "Id", @property.AppUserId);
            ViewData["AreaId"] = new SelectList(_context.Areas, "AreaId", "AreaName", @property.AreaId);
            ViewData["CategorayId"] = new SelectList(_context.Categoraies, "CategorayId", "CategorayName", @property.CategorayId);
            return View(@property);
        }

        // POST: Properties/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PropertyId,PropertyTitle,PropertyDescription,PropertyCapacity,PropertyBedsNum,PropertyBedRooms,PropertyBath,PropertyPricePerNight,PropertyHostInfo,AppUserId,AreaId,CategorayId")] Property @property)
        {
            if (id != @property.PropertyId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(@property);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PropertyExists(@property.PropertyId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AppUserId"] = new SelectList(_context.Users, "Id", "Id", @property.AppUserId);
            ViewData["AreaId"] = new SelectList(_context.Areas, "AreaId", "AreaName", @property.AreaId);
            ViewData["CategorayId"] = new SelectList(_context.Categoraies, "CategorayId", "CategorayName", @property.CategorayId);
            return View(@property);
        }

        // GET: Properties/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Properties == null)
            {
                return NotFound();
            }

            var @property = await _context.Properties
                .Include(z => z.AppUser)
                .Include(z => z.Area)
                .Include(z => z.Categoray)
                .FirstOrDefaultAsync(m => m.PropertyId == id);
            if (@property == null)
            {
                return NotFound();
            }

            return View(@property);
        }

        // POST: AdminProperties/Delete/5

AirBnB/AirBnB/Views/Properties/AdminDetails.cshtml
@model AirBnB.Models.Property

@{
    ViewData["Title"] = "Details";
}
<div class="container" style="text-align:center">
    <h1>Details</h1>
    <div>
        <a asp-action="Delete">Delete</a>
    </div>
    <div>
        <h4>Property</h4>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.PropertyTitle)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.PropertyTitle)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.PropertyDescription)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.PropertyDescription)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.PropertyCapacity)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.PropertyCapacity)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.PropertyBedsNum)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.PropertyBedsNum)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.PropertyBedRooms)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.PropertyBedRooms)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.PropertyBath)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.PropertyBath)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.PropertyPricePerNight)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.PropertyPricePerNight)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.PropertyHostInfo)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.PropertyHostInfo)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.AppUser)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.AppUser.Id)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Area)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Area.AreaName)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Categoray)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Categoray.CategorayName)
            </dd>
        </dl>
    </div>
    <div>
        <a asp-action="AdminIndex">Back to List</a>
    </div>
</div>

AirBnB/AirBnB/Views/Properties/AdminIndex.cshtml
@inject UserManager<AppUser> UserManager
@model IEnumerable<AirBnB.Models.Property>

@{
    ViewData["Title"] = "Index";
}
<div class="container" style="text-align:center">
    <h1>Properties</h1>
    <table class="table table-dark table-hover">
        <thead>
            <tr>
                <th>
                    Title
                </th>
                <th>
                    Price Per Night
                </th>
                <th>
                    User
                </th>
                <th>
                    Manage
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                var user = UserManager.Users.FirstOrDefault(a => a.Id == item.AppUserId);
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.PropertyTitle)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PropertyPricePerNight)
                    </td>
                    <td>
                        @user.Email
                    </td>
                    <td>
                        <a asp-action="AdminDetails" asp-route-id="@item.PropertyId">All Details</a> |
                        <a class="btn btn-info" asp-controller="Properties" asp-action="Confirm" asp-route-id="@item.PropertyId">Confirm</a>|
                        <a class="btn btn-danger" asp-controller="Properties" asp-action="Reject" asp-route-id="@item.PropertyId">Reject</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

AirBnB/AirBnB/Views/Properties/Create.cshtml
@model AirBnB.Models.Property

@{
    ViewData["Title"] = "Create";
}

@*<div class="createbackground">*@

@*Neamaaaaaaaaaaaaaaaaaaaaaaa*@
@*Start*@
<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-push-6">
            <div class="start">
                <h1 fw-bolder> It’s easy to get <br>started on Airbnb</h1>
            </div>
        </div>
        <div class="col-md-6 col-md-push-5 ">
            <div class=" mt-5">
                <div class=" text-md-right pb-3">
                    <h4 fw-bolder text-dark>
                        1 Tell us about your place
                    </h4>
                    <div class="row">
                        <h5 class="col-md-8 col-md-push-8 text-secondary ms-3">
                            Share some basic info, like where it is and how many guests can stay.
                        </h5>
                        <img class="col-md-3 col-md-push-3" src="~/createimgs/$RL20YJP.png" style="background-color:darkgrey"/>
                    </div>
                </div>
                <!-- 2 -->
                <hr class="m-6">
                <div class=" text-md-right pt-3">
                    <h4 fw-bolder text-dark>
                        2 Make it stand out
                    </h4>
                    <div class="row pb-3">
                        <h5 class="col-md-8 col-md-push-8 text-secondary ms-3">
                            Add 5 or more photos plus a title and description—we’ll help you out.
                        </h5>
                        <img class="col-md-3 col-md-push-3" src="~/createimgs/$RR96XHQ.png" />
                    </div>
                    <!-- 3 -->
                    <hr class="m-6">
                    <div class=" text-md-right pt-3">
                        <div class="row pb-2">
                            <h4 fw-bolder text-dark>
                                3 Finish up and publish
                            </h4>
                            <h5 class="col-md-8 col-md-push-8 text-secondary ms-3">
                                Choose if you'd like to start with an experienced guest, set a starting price, and publish your listing.
                            </h5>
                            <img class="col-md-3 col-md-push-3 " src="~/createimgs/$RDT168S.jpg" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    @*Start*@

    <!-- slide 1 -->

    <hr class="m-2">

    <div class="row">
        <div class="col-md-6 col-md-push-7">
            <div class="steps">
                <p fw-bold>Step 1</p>
                <h1>Tell us about your place</h1>
                <p>
                    In this step, we'll ask you which type of property you have and if guests will book the entire place or
                    just a room. Then let us know the location and how many guests can stay.
                </p>
            </div>
        </div>

        <div class="col-md-6 col-md-push-5 ">
            <div class=" mt-2">
                <div class=" text-md-right">
                    <img class="col-lg-12 col-lg-push-14" src="~/createimgs/$RGZEF4E.gif">
                </div>
            </div>
        </div>
    </div>

    <hr class="m-6">
    <!--  /slide 1 -->
    @*Neamaaaaaaaaaaaaaaaaaaaaaaa*@



    <form asp-action="Create" enctype="multipart/form-data">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="row">
            <div class="col-9 offset-2">
                <div class="form-group">
                    @* <!-- 2 --> *@
                    <h2 class="properties-headers">
                        Which of these best describes your place?
                    </h2>
                    <div class="row">
                        @foreach (var cat in ViewBag.cat)
                        {
                            <label id="radbtn-@cat.CategorayId" class="col-3 m-2 p-3 rounded-3 text-start btns">
                                <div class="p-2">
                                    <div>
                                        <img class="icons-image" src="~/CategoryImgs/@cat.Categoryphotosrc" alt="option 1" />
                                    </div>
                                    <input type="radio" asp-for="CategorayId" value="@cat.CategorayId" onclick="myfunc('radbtn-'+@cat.CategorayId)" class="opacity-0 btns" />
                                    @cat.CategorayName
                                </div>
                            </label>
                        }
                    </div>
                </div>

                <div class="col-9">
                    <h2 class="properties-headers mb-3">
                        Where's your place located?
                    </h2>
                    <div class="form-group">
                        <select asp-for="AreaId" class="form-control select-loc mb-3" asp-items="ViewBag.AreaId"></select>
                    </div>
                </div>
            </div>


            @*Dohaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa*@


            @*Neamaaaaaaaaaaaaaaaaaaaaaaa*@

            <!-- slide2 -->

            <hr class="mt-4" style="width:96%;margin-left:6px">
            <div class="row">
                <div class="col-md-6 col-md-push-7">
                    <div class="steps">
                        <p fw-bold>Step 2</p>
                        <h1>Make your place <br> stand out</h1>
                        <p>
                            In this step, you’ll add some of the amenities your place offers, plus 5 or more photos. Then, you’ll
                            create a title and description.
                        </p>
                    </div>
                </div>

                <div class="col-md-6 col-md-push-5 ">
                    <div class=" mt-5">
                        <div class=" text-md-right">
                            <img class="col-lg-12 col-lg-push-14" src="~/createimgs/$RV1554R.jpg">
                        </div>
                    </div>
                </div>
            </div>
            <hr class="mt-4" style="width:96%;margin-left:6px">

            <!-- /slide2 -->
            @*Neamaaaaaaaaaaaaaaaaaaaaaaa*@
            @*     Amenities     *@
            <div class="form-group">
                <div class="col-9 offset-2">
                    <div class="row">
                        <h2 class="properties-headers mb-3">
                            Tell guests what your place has to offer
                        </h2>
                        <p class="text-secondary">You can add more amenities after you publish your listing.</p>
                        @foreach (var item in ViewBag.Amenity as List<Amenity>)
                        {
                            @*<div class="p-2">*@
                            <label id="radbtnamenity-@item.AmenityId" class="col-3 m-2 p-3 rounded-3 text-start btns">
                                <div>
                                    <img class="icons-image" src="~/AmenityImg/@item.AmenityImgSrc" alt="option 1" />
                                </div>
                                <input type="checkbox" name="amenity" value="@item.AmenityId" class="opacity-0 btns" onclick="multiplefunction('radbtnamenity-'+@item.AmenityId)" autocomplete="off">
                                @item.AmenityName
                            </label>
                            @*</div>*@
                        }
                    </div>
                </div>

                @*imageeeeeeeeeeeeeeeeeeeeeeeees*@
                <div class="col-7 offset-2">

                    <h2 class="properties-headers mb-3">
                        Add some photos of your boat
                    </h2>
                    <p class="text-secondary">You'll need 5 photos to get started. You can add more or make changes later.</p>
                    <div class="pictures">
                        <div class="text-center photostexts">
                            <img src="/Icons_Imgs/photos.png" alt="photos" class="photo">
                            <h3>Drag your photos here</h3>
                            <h6 class="fw-normal fs-5 text-center">Choose at least 5 photos</h6>
                            <input id="files" type="file" name="propImg" class="offset-2" multiple />
                        </div>
                    </div>

                    @*enter your property title*@
                    <div class="form-group">
                        <h2 asp-for="PropertyTitle" class="control-label properties-headers mb-2">Now, let's give your boat a title</h2>
                        <p class="text-secondary">Short titles work best. Have fun with it—you can always change it later.</p>
                        <textarea asp-for="PropertyTitle" rows="5" cols="80" class="form-control inputs rounded-3 textarea fs-5 mt-3 p-3"></textarea>

                        @*<input asp-for="PropertyTitle" class="form-control inputs" />*@
                        <span asp-validation-for="PropertyTitle" class="text-danger"></span>
                    </div>

                    @*enter your property description *@
                    <div class="form-group mb-1">
                        <h2 asp-for="PropertyDescription" class="control-label properties-headers mb-2">Create your description</h2>
                        <p class="text-secondary">Share what makes your place special.</p>
                        @**input asp-for="PropertyDescription" class="form-control inputs" /> *@
                        <textarea rows="6" cols="55" class="form-control inputs rounded-3 textarea mb-4 p-3 fs-5 placeholder=" This place to stay is truly one of a kind.""
                                  asp-for="PropertyDescription"></textarea>
                        <span asp-validation-for="PropertyDescription" class="text-danger"></span>
                    </div>
                </div>
            </div>
        </div>


        @*Neamaaaaaaaaaaaaaaaaaaaaaaa*@

        <!-- slide3 -->
        <hr class="m-2">
        <div class="row">
            <div class="col-md-6 col-md-push-7 ">
                <div class="steps">
                    <p>Step 3</p>
                    <h1>Finish up and publish</h1>
                    <p>
                        Finally, you’ll choose if you'd like to start with an experienced guest, then you'll set your nightly
                        price. Answer a few quick questions and publish when you're ready.
                    </p>

                </div>
            </div>

            <div class="col-md-6 col-md-push-5 ">
                <div class=" mt-2">
                    <div class=" text-md-right">
                        <img class="col-lg-12 col-lg-push-14" src="~/createimgs/$RPIW7AV.gif">
                    </div>
                </div>
            </div>
        </div>
        <hr class="m-3">

        <!-- /slide3 -->
        @*Neamaaaaaaaaaaaaaaaaaaaaaaa*@

        <div class="row">
            <div class="col-7 offset-2">
                <div class="form-group">
                    <label asp-for="PropertyCapacity" class="control-label texts fw-bold"></label>
                    <input asp-for="PropertyCapacity" class="form-control inputs" />
                    <span asp-validation-for="PropertyCapacity" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="PropertyBedsNum" class="control-label texts fw-bold"></label>
                    <input asp-for="PropertyBedsNum" class="form-control inputs" />
                    <span asp-validation-for="PropertyBedsNum" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="PropertyBedRooms" class="control-label texts fw-bold"></label>
                    <input asp-for="PropertyBedRooms" class="form-control inputs" />
                    <span asp-validation-for="PropertyBedRooms" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="PropertyBath" class="control-label texts fw-bold"></label>
                    <input asp-for="PropertyBath" class="form-control inputs" />
                    <span asp-validation-for="PropertyBath" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="PropertyPricePerNight" class="control-label texts fw-bold"></label>
                    <input asp-for="PropertyPricePerNight" class="form-control inputs" />
                    <span asp-validation-for="PropertyPricePerNight" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="PropertyHostInfo" class="control-label texts fw-bold"></label>
                    @**input asp-for="PropertyHostInfo" class="form-control inputs" />*@
                    <textarea rows="4" cols="80" class="form-control inputs fs-5"
                              asp-for="PropertyHostInfo"></textarea>
                    <span asp-validation-for="PropertyHostInfo" class="text-danger"></span>
                </div>
                <div class="form-group">

                    <input asp-for="AppUserId" class="form-control" value='@ViewData["userid"]' type="hidden" />
                </div>



                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-outline-info offset-4 mt-4 fs-5 fw-bold submitbtn" />
                </div>
            </div>
        </div>
    </form>
</div>
@*</div>*@


<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }