AirBnB/AirBnB/Models/Categoray.cs
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.ComponentModel.DataAnnotations;

namespace AirBnB.Models
{
    public class Categoray
    {
        [Key]
        public int CategorayId { get; set; }
        [Required]
        public string CategorayName { get; set; }
        //NP
        public ICollection<Property> Properties { get; set; } = new HashSet<Property>();

        public string Categoryphotosrc { get; set; }

    }
}

AirBnB/AirBnB/Controllers/CategoraysController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AirBnB.Data;
using AirBnB.Models;
using System.Data;
using Microsoft.AspNetCore.Authorization;

namespace AirBnB.Controllers
{
    public class CategoraysController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CategoraysController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Categorays
        public async Task<IActionResult> Index()
        {
              return View(await _context.Categoraies.ToListAsync());
        }

        public async Task<IActionResult> ShowProp(int id)
        {
            var PropList = _context.Properties.Include(z => z.AppUser).Include(z => z.Area).ThenInclude(z => z.City).Include(z => z.Categoray).Include(z => z.PropertyImgs).Where(a => a.CategorayId == id &&a.Accepted==true);
            var categories = _context.Categoraies;
            ViewBag.cat = categories;
            return View(PropList);
        }

        // GET: Categorays/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Categoraies == null)
            {
                return NotFound();
            }

            var categoray = await _context.Categoraies.Include(D => D.Properties).ThenInclude(z =>z.Area).ThenInclude(z =>z.City)
                .FirstOrDefaultAsync(m => m.CategorayId == id);
            ViewBag.catphotos = await _context.Categoraies.Include(z => z.Properties).ThenInclude(z => z.PropertyImgs).FirstOrDefaultAsync(m => m.CategorayId == id);
            if (categoray == null)
            {
                return NotFound();
            }

            return View(categoray);
        }

        // GET: Categorays/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }



        // POST: Categorays/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create([Bind("CategorayId,CategorayName")] Categoray categoray, IFormFile imgFile)
        {
            if (ModelState.IsValid)
            {
                
                var lastrow = _context.Categoraies.OrderByDescending(u => u.CategorayId).FirstOrDefault();
                if (lastrow != null)
                {
                    int lastid = lastrow.CategorayId;
                    string fileName = (lastid + 1).ToString() + "." + imgFile.FileName.Split(".").Last();
                    categoray.Categoryphotosrc = fileName;
                    using (var fs = System.IO.File.Create("wwwroot/CategoryImgs/" + fileName))
                    {
                        imgFile.CopyTo(fs);
                    }
                    _context.Add(categoray);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    string fileName = categoray.CategorayId.ToString() + "." + imgFile.FileName.Split(".").Last();
                    categoray.Categoryphotosrc = fileName;
                    using (var fs = System.IO.File.Create("wwwroot/CategoryImgs/" + fileName))
                    {
                        imgFile.CopyTo(fs);
                    }
                    _context.Add(categoray);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
            }
            return View(categoray);
        }


        // GET: Categorays/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Categoraies == null)
            {
                return NotFound();
            }

            var categoray = await _context.Categoraies.FindAsync(id);
            if (categoray == null)
            {
                return NotFound();
            }
            return View(categoray);
        }

        // POST: Categorays/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, [Bind("CategorayId,CategorayName")] Categoray categoray, IFormFile imgFile)
        {
            if (id != categoray.CategorayId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (imgFile != null)
                    {
                        string fileName = categoray.CategorayId.ToString() + "." + imgFile.FileName.Split(".").Last();
                        if (System.IO.File.Exists("wwwroot/CategoryImgs/" + fileName))
                        {
                            System.IO.File.Delete("wwwroot/CategoryImgs/" + fileName);
                        }
                        using (var fs = System.IO.File.Create("wwwroot/CategoryImgs/" + fileName))
                        {
                            imgFile.CopyTo(fs);
                        }
                        categoray.Categoryphotosrc = fileName;
                    }
                    _context.Update(categoray);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategorayExists(categoray.CategorayId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(categoray);
        }

        // GET: Categorays/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Categoraies == null)
            {
                return NotFound();
            }

            var categoray = await _context.Categoraies
                .FirstOrDefaultAsync(m => m.CategorayId == id);
            if (categoray == null)
            {
                return NotFound();
            }

            return View(categoray);
        }

        // POST: Categorays/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Categoraies == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Categoraies'  is null.");
            }
            var categoray = await _context.Categoraies.FindAsync(id);
            if (categoray != null)
            {
                string fileName = categoray.Categoryphotosrc;
                if (System.IO.File.Exists("wwwroot/CategorayImgs/" + fileName))
                {
                    System.IO.File.Delete("wwwroot/CategorayImgs/" + fileName);
                }
                _context.Categoraies.Remove(categoray);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CategorayExists(int id)
        {
          return _context.Categoraies.Any(e => e.CategorayId == id);
        }
    }
}

AirBnB/AirBnB/Views/Categorays/Create.cshtml
@model AirBnB.Models.Categoray

@{
    ViewData["Title"] = "Create";
}

<div class="edit">
    <form asp-action="Create" enctype="multipart/form-data">

        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        @*================================================================*@
        <label class="lblName" for="Name">Add The Categoray Name</label>
        <br>
        <input asp-for="CategorayName" type="text" id="Name">
        <span asp-validation-for="CategorayName" class="text-danger"></span>
        @*================================================================*@
        <div class="upload-img">
            <label class="lblImg">Add The Categoray Image</label>
            <br>
            <input type="file" id="file-1" accept="image/*" name="imgFile">

            <label for="file-1" id="file-1-preview">
                <img src="https://bit.ly/3ubuq5o" alt="Categoray Image">
                <span>+</span>
            </label>
        </div>
        @*================================================================*@
        <input type="submit" value="Add">
        @*================================================================*@
        <a class="backLink" asp-action="Index">Back</a>
    </form>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AirBnB/AirBnB/Views/Categorays/Delete.cshtml
@model AirBnB.Models.Categoray

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Categoray</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CategorayName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CategorayName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="CategorayId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

AirBnB/AirBnB/Views/Categorays/Details.cshtml
@model AirBnB.Models.Categoray

@{
    ViewData["Title"] = "Details";
}


<div class="info">
    <div class="container">
        <div class="row details">
            <div class="col-5 image">
                <img src="/CategoryImgs/@Model.Categoryphotosrc" alt="" class="AmenityImg">
            </div>
            <div class="col-4 text align-self-center">
                <h1>@Model.CategorayName</h1>
                @if (User.IsInRole("Admin"))
                {
                    <a asp-action="Index">Back To List</a>
                    <a asp-action="Edit" asp-route-id="@Model.CategorayId">Edit</a>
                }
            </div>
        </div>
    </div>
</div>







@*<div class="container" style="margin-top:40px">
    <div class="row bg">
        @foreach (var item in Model.Properties)
        {
            var photos = item.PropertyImgs.ToList();
            <div class="col-4">
                <div class="card ">
                    <div id="carouselExample_@item.PropertyId" class="carousel slide h-100">
                        <div class="carousel-inner">
                            @for (int i = 0; i < photos.Count(); i++)
                            {
                                if (i == 0)
                                {
                                    <div class="carousel-item active">
                                        <img src="~/Images/@photos[i].ImgSrc" width="300" height="300" class="d-block w-100 rounded" />
                                    </div>
                                }
                                else
                                {
                                    <div class="carousel-item">
                                        <img src="~/Images/@photos[i].ImgSrc" width="330" height="330" class="d-block w-100" />
                                    </div>
                                }

                            }
                        </div>
                        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample_@item.PropertyId" data-bs-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="visually-hidden">Previous</span>
                        </button>
                        <button class="carousel-control-next" type="button" data-bs-target="#carouselExample_@item.PropertyId" data-bs-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="visually-hidden">Next</span>
                        </button>
                    </div>


                    <div class="card-body">
                        <h5 class="card-title">@item.PropertyTitle</h5>
                        <p class="card-text">
                            <small class="text-muted">@item.PropertyDescription</small>
                        </p>
                        <p class="card-text m-md-n5" style="margin: -10px 0;">
                            <small class="text-muted">@item.PropertyBedsNum beds</small>
                        </p>
                    </div>
                    <div class="card-footer border-0 bg-transparent ">
                        <small class="text-muted"><span>@item.PropertyPricePerNight</span>$ per night</small>
                    </div>
                    <div>
                        <a asp-controller="Bookings" asp-action="Create" asp-route-id="@item.PropertyId">Book</a>
                    </div>

                </div>
            </div>
        }
    </div>
</div>*@

AirBnB/AirBnB/Views/Categorays/Edit.cshtml
@model AirBnB.Models.Categoray

@{
    ViewData["Title"] = "Edit";
}

<div class="edit">
    <form asp-action="Edit" enctype="multipart/form-data">

        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="CategorayId" />
        @*================================================================*@
        <label class="lblName" for="Name">Update The Categoray Name</label>
        <br>
        <input asp-for="CategorayName" type="text" id="Name">
        <span asp-validation-for="CategorayName" class="text-danger"></span>
        @*================================================================*@
        <div class="upload-img">
            <label class="lblImg">Update The Categoray Image</label>
            <br>
            <input type="file" id="file-1" accept="image/*" name="imgFile">

            <label for="file-1" id="file-1-preview" class="AmenityImg">
                <img src="/CategoryImgs/@Model.Categoryphotosrc" alt="City Image">
                <span>+</span>
            </label>
        </div>
        @*================================================================*@
        <input type="submit" value="Update">
        @*================================================================*@
        <a class="backLink" asp-action="Index">Back</a>
    </form>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AirBnB/AirBnB/Views/Categorays/Index.cshtml
@model IEnumerable<AirBnB.Models.Categoray>

@{
    ViewData["Title"] = "Index";
}
<div class="container" style="text-align:center">

<h1>Categorays</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
    <table class="table table-dark table-hover">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CategorayName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CategorayName)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.CategorayId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.CategorayId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.CategorayId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>
</div>

AirBnB/AirBnB/Views/Categorays/ShowProp.cshtml
@model IEnumerable<AirBnB.Models.Property>
@{
    ViewData["Title"] = "ShowProp";
}

<style>
    .aa {
        height: 27rem;
        margin-bottom: 15px;
        border-radius: 15px;
    }

    .bb {
        height: 14rem;
        border-radius: 10px 10px 0 0;
    }

    .cc {
        height: 18rem;
    }
</style>


<div class="container">
    <div class="row bg">
        <div>
            <div class="d-flex my-2 border d-flex justify-content-center mb-4">
                @foreach (var item1 in ViewBag.cat)
                {
                    <div class=" d-flex flex-column mx-4 ">

                        <a asp-controller="Categorays" asp-action="ShowProp" asp-route-id="@item1.CategorayId"><img class="icons-image" src="/CategoryImgs/@item1.Categoryphotosrc" alt="Categoray Image" style="width:60px;height:60px;margin-bottom:-15px" /></a>
                        <a class="text-dark" asp-controller="Categorays" asp-action="ShowProp" asp-route-id="@item1.CategorayId">@item1.CategorayName</a>
                    </div>
                }
            </div>
        </div>
        @foreach (var item in Model)
        {
            var photos = item.PropertyImgs.ToList();
            <div class="col-lg-3 col-md-6 col-sm-12">
                <div class="card aa ">
                    <div id="carouselExample_@item.PropertyId" class="carousel slide h-100">
                        <div class="carousel-inner bb">
                            @for (int i = 0; i < photos.Count(); i++)
                            {
                                if (i == 0)
                                {
                                    <div class="carousel-item active">
                                        <img src="~/Images/@photos[i].ImgSrc" style="width:15rem; height:15rem;border-radius:0.8rem" class="d-block w-100 " />
                                    </div>
                                }
                                else
                                {
                                    <div class="carousel-item">
                                        <img src="~/Images/@photos[i].ImgSrc" style="width:20rem; height:20rem;border-radius:0.8rem" class="d-block w-100" />
                                    </div>
                                }
                            }
                        </div>
                        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample_@item.PropertyId" data-bs-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="visually-hidden">Previous</span>
                        </button>
                        <button class="carousel-control-next" type="button" data-bs-target="#carouselExample_@item.PropertyId" data-bs-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="visually-hidden">Next</span>
                        </button>
                    </div>
                    <div class=" cc card-body">
                        <h5 class="card-title">@item.PropertyTitle</h5>
                        <p class="card-text">
                            <small class="text-muted">@item.PropertyDescription</small>
                        </p>
                        <p class="card-text m-md-n5" style="margin: -10px 0;">
                            <small class="text-muted">@item.PropertyBedsNum beds</small>
                        </p>
                    </div>
                    <div class="card-footer border-0 bg-transparent  ">
                        <small><span class="h6 ">@item.PropertyPricePerNight$</span> <span class="text-muted">per night</span></small>
                    </div>
                    <div class="m-auto">
                        <a asp-controller="Properties" asp-action="Details" asp-route-id="@item.PropertyId" class="btn btn-primary h-50 px-5 m-1 " style="padding-bottom:25px ">Details</a>

                        @*                        <a asp-controller="Bookings" asp-action="Create" asp-route-id="@item.PropertyId">Book</a>
                    *@
                    </div>

                </div>
            </div>
        }
    </div>
</div>